num1 = 1;
console.log(`El numero ${num1} es ` + Boolean(num1));
num1 = -2;
console.log(`El numero ${num1} es ` + Boolean(num1));
num1 = "Hello";
console.log(`El numero ${num1} es ` + Boolean(num1));
num1 = Infinity;
console.log(`El numero ${num1} es ` + Boolean(num1));
num1 = 0;
console.log(`El numero ${num1} es ` + Boolean(num1));
num1 = "";
console.log(`El numero ${num1} es ` + Boolean(num1));
num1 = NaN;
console.log(`El numero ${num1} es ` + Boolean(num1));
num1 = null;
console.log(`El numero ${num1} es ` + Boolean(num1));
num1 = 0 / 0;
console.log(`El numero ${num1} es ` + Boolean(num1));